# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_new_point.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddNewPointDialog(object):
    def setupUi(self, AddNewPointDialog):
        AddNewPointDialog.setObjectName("AddNewPointDialog")
        AddNewPointDialog.resize(278, 287)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddNewPointDialog.sizePolicy().hasHeightForWidth())
        AddNewPointDialog.setSizePolicy(sizePolicy)
        AddNewPointDialog.setMinimumSize(QtCore.QSize(0, 0))
        AddNewPointDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        AddNewPointDialog.setAccessibleName("")
        AddNewPointDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.verticalLayout = QtWidgets.QVBoxLayout(AddNewPointDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.AddNewPointGroup = QtWidgets.QGroupBox(AddNewPointDialog)
        self.AddNewPointGroup.setObjectName("AddNewPointGroup")
        self.formLayout = QtWidgets.QFormLayout(self.AddNewPointGroup)
        self.formLayout.setObjectName("formLayout")
        self.PointNumberLabel = QtWidgets.QLabel(self.AddNewPointGroup)
        self.PointNumberLabel.setObjectName("PointNumberLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.PointNumberLabel)
        self.PointNumberLineEdit = QtWidgets.QLineEdit(self.AddNewPointGroup)
        self.PointNumberLineEdit.setObjectName("PointNumberLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.PointNumberLineEdit)
        self.EastCoordLabel = QtWidgets.QLabel(self.AddNewPointGroup)
        self.EastCoordLabel.setObjectName("EastCoordLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.EastCoordLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.EastCoordLineEdit = QtWidgets.QLineEdit(self.AddNewPointGroup)
        self.EastCoordLineEdit.setObjectName("EastCoordLineEdit")
        self.horizontalLayout_4.addWidget(self.EastCoordLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.NorthCoordLabel = QtWidgets.QLabel(self.AddNewPointGroup)
        self.NorthCoordLabel.setObjectName("NorthCoordLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.NorthCoordLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.NorthCoordLineEdit = QtWidgets.QLineEdit(self.AddNewPointGroup)
        self.NorthCoordLineEdit.setObjectName("NorthCoordLineEdit")
        self.horizontalLayout_3.addWidget(self.NorthCoordLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.ZCoordLabel = QtWidgets.QLabel(self.AddNewPointGroup)
        self.ZCoordLabel.setObjectName("ZCoordLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ZCoordLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ZCoordLineEdit = QtWidgets.QLineEdit(self.AddNewPointGroup)
        self.ZCoordLineEdit.setObjectName("ZCoordLineEdit")
        self.horizontalLayout_2.addWidget(self.ZCoordLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.PointCodeLabel = QtWidgets.QLabel(self.AddNewPointGroup)
        self.PointCodeLabel.setObjectName("PointCodeLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.PointCodeLabel)
        self.PointCodeLineEdit = QtWidgets.QLineEdit(self.AddNewPointGroup)
        self.PointCodeLineEdit.setObjectName("PointCodeLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.PointCodeLineEdit)
        self.PointTypeLabel = QtWidgets.QLabel(self.AddNewPointGroup)
        self.PointTypeLabel.setObjectName("PointTypeLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.PointTypeLabel)
        self.PointTypeLineEdit = QtWidgets.QLineEdit(self.AddNewPointGroup)
        self.PointTypeLineEdit.setObjectName("PointTypeLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.PointTypeLineEdit)
        self.verticalLayout.addWidget(self.AddNewPointGroup)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.AddButton = QtWidgets.QPushButton(AddNewPointDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddButton.sizePolicy().hasHeightForWidth())
        self.AddButton.setSizePolicy(sizePolicy)
        self.AddButton.setObjectName("AddButton")
        self.horizontalLayout.addWidget(self.AddButton)
        self.ResetButton = QtWidgets.QPushButton(AddNewPointDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResetButton.sizePolicy().hasHeightForWidth())
        self.ResetButton.setSizePolicy(sizePolicy)
        self.ResetButton.setObjectName("ResetButton")
        self.horizontalLayout.addWidget(self.ResetButton)
        self.CloseButton = QtWidgets.QPushButton(AddNewPointDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CloseButton.sizePolicy().hasHeightForWidth())
        self.CloseButton.setSizePolicy(sizePolicy)
        self.CloseButton.setObjectName("CloseButton")
        self.horizontalLayout.addWidget(self.CloseButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.PointNumberLabel.setBuddy(self.PointNumberLineEdit)
        self.EastCoordLabel.setBuddy(self.EastCoordLineEdit)
        self.NorthCoordLabel.setBuddy(self.NorthCoordLineEdit)
        self.ZCoordLabel.setBuddy(self.ZCoordLineEdit)
        self.PointCodeLabel.setBuddy(self.PointCodeLineEdit)
        self.PointTypeLabel.setBuddy(self.PointTypeLineEdit)

        self.retranslateUi(AddNewPointDialog)
        QtCore.QMetaObject.connectSlotsByName(AddNewPointDialog)
        AddNewPointDialog.setTabOrder(self.PointNumberLineEdit, self.EastCoordLineEdit)
        AddNewPointDialog.setTabOrder(self.EastCoordLineEdit, self.NorthCoordLineEdit)
        AddNewPointDialog.setTabOrder(self.NorthCoordLineEdit, self.ZCoordLineEdit)
        AddNewPointDialog.setTabOrder(self.ZCoordLineEdit, self.PointCodeLineEdit)
        AddNewPointDialog.setTabOrder(self.PointCodeLineEdit, self.PointTypeLineEdit)
        AddNewPointDialog.setTabOrder(self.PointTypeLineEdit, self.AddButton)
        AddNewPointDialog.setTabOrder(self.AddButton, self.ResetButton)
        AddNewPointDialog.setTabOrder(self.ResetButton, self.CloseButton)

    def retranslateUi(self, AddNewPointDialog):
        _translate = QtCore.QCoreApplication.translate
        AddNewPointDialog.setWindowTitle(_translate("AddNewPointDialog", "Add New Point"))
        self.AddNewPointGroup.setTitle(_translate("AddNewPointDialog", "Add New Point with Coordinates"))
        self.PointNumberLabel.setText(_translate("AddNewPointDialog", "&Point ID"))
        self.EastCoordLabel.setText(_translate("AddNewPointDialog", "&East"))
        self.NorthCoordLabel.setText(_translate("AddNewPointDialog", "&North"))
        self.ZCoordLabel.setText(_translate("AddNewPointDialog", "Ele&vation"))
        self.PointCodeLabel.setText(_translate("AddNewPointDialog", "Point &Code"))
        self.PointTypeLabel.setText(_translate("AddNewPointDialog", "Point &Type"))
        self.AddButton.setText(_translate("AddNewPointDialog", "Add"))
        self.ResetButton.setText(_translate("AddNewPointDialog", "Reset"))
        self.CloseButton.setText(_translate("AddNewPointDialog", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddNewPointDialog = QtWidgets.QDialog()
    ui = Ui_AddNewPointDialog()
    ui.setupUi(AddNewPointDialog)
    AddNewPointDialog.show()
    sys.exit(app.exec_())

