# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plugin_settings.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PluginSettingsDialog(object):
    def setupUi(self, PluginSettingsDialog):
        PluginSettingsDialog.setObjectName("PluginSettingsDialog")
        PluginSettingsDialog.resize(391, 412)
        self.verticalLayout = QtWidgets.QVBoxLayout(PluginSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SettingsTab = QtWidgets.QTabWidget(PluginSettingsDialog)
        self.SettingsTab.setObjectName("SettingsTab")
        self.tabDirectories = QtWidgets.QWidget()
        self.tabDirectories.setObjectName("tabDirectories")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabDirectories)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.HomeDirLabel = QtWidgets.QLabel(self.tabDirectories)
        self.HomeDirLabel.setObjectName("HomeDirLabel")
        self.verticalLayout_2.addWidget(self.HomeDirLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.HomeDirEdit = QtWidgets.QLineEdit(self.tabDirectories)
        self.HomeDirEdit.setReadOnly(True)
        self.HomeDirEdit.setObjectName("HomeDirEdit")
        self.horizontalLayout_5.addWidget(self.HomeDirEdit)
        self.HomeDirButton = QtWidgets.QToolButton(self.tabDirectories)
        self.HomeDirButton.setObjectName("HomeDirButton")
        self.horizontalLayout_5.addWidget(self.HomeDirButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.LogPathLabel = QtWidgets.QLabel(self.tabDirectories)
        self.LogPathLabel.setObjectName("LogPathLabel")
        self.verticalLayout_2.addWidget(self.LogPathLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LogPathEdit = QtWidgets.QLineEdit(self.tabDirectories)
        self.LogPathEdit.setReadOnly(True)
        self.LogPathEdit.setObjectName("LogPathEdit")
        self.horizontalLayout_4.addWidget(self.LogPathEdit)
        self.LogPathButton = QtWidgets.QToolButton(self.tabDirectories)
        self.LogPathButton.setObjectName("LogPathButton")
        self.horizontalLayout_4.addWidget(self.LogPathButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.LogPathLabel_2 = QtWidgets.QLabel(self.tabDirectories)
        self.LogPathLabel_2.setObjectName("LogPathLabel_2")
        self.verticalLayout_2.addWidget(self.LogPathLabel_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.GamaPathEdit = QtWidgets.QLineEdit(self.tabDirectories)
        self.GamaPathEdit.setReadOnly(True)
        self.GamaPathEdit.setObjectName("GamaPathEdit")
        self.horizontalLayout_3.addWidget(self.GamaPathEdit)
        self.GamaPathButton = QtWidgets.QToolButton(self.tabDirectories)
        self.GamaPathButton.setObjectName("GamaPathButton")
        self.horizontalLayout_3.addWidget(self.GamaPathButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.LogPathLabel_3 = QtWidgets.QLabel(self.tabDirectories)
        self.LogPathLabel_3.setObjectName("LogPathLabel_3")
        self.verticalLayout_2.addWidget(self.LogPathLabel_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PlotTemplateDirEdit = QtWidgets.QLineEdit(self.tabDirectories)
        self.PlotTemplateDirEdit.setReadOnly(True)
        self.PlotTemplateDirEdit.setObjectName("PlotTemplateDirEdit")
        self.horizontalLayout_2.addWidget(self.PlotTemplateDirEdit)
        self.PlotTemplateDirButton = QtWidgets.QToolButton(self.tabDirectories)
        self.PlotTemplateDirButton.setObjectName("PlotTemplateDirButton")
        self.horizontalLayout_2.addWidget(self.PlotTemplateDirButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 85, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.SettingsTab.addTab(self.tabDirectories, "")
        self.tabFont = QtWidgets.QWidget()
        self.tabFont.setObjectName("tabFont")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabFont)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.FontLabel = QtWidgets.QLabel(self.tabFont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FontLabel.sizePolicy().hasHeightForWidth())
        self.FontLabel.setSizePolicy(sizePolicy)
        self.FontLabel.setScaledContents(False)
        self.FontLabel.setWordWrap(True)
        self.FontLabel.setObjectName("FontLabel")
        self.verticalLayout_3.addWidget(self.FontLabel)
        self.FontNameLabel = QtWidgets.QLabel(self.tabFont)
        self.FontNameLabel.setObjectName("FontNameLabel")
        self.verticalLayout_3.addWidget(self.FontNameLabel)
        self.FontNameCombo = QtWidgets.QFontComboBox(self.tabFont)
        self.FontNameCombo.setEditable(False)
        self.FontNameCombo.setFontFilters(QtWidgets.QFontComboBox.MonospacedFonts)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        self.FontNameCombo.setCurrentFont(font)
        self.FontNameCombo.setObjectName("FontNameCombo")
        self.verticalLayout_3.addWidget(self.FontNameCombo)
        self.FontSizeLabel = QtWidgets.QLabel(self.tabFont)
        self.FontSizeLabel.setObjectName("FontSizeLabel")
        self.verticalLayout_3.addWidget(self.FontSizeLabel)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.FontSizeCombo = QtWidgets.QComboBox(self.tabFont)
        self.FontSizeCombo.setObjectName("FontSizeCombo")
        self.horizontalLayout_6.addWidget(self.FontSizeCombo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 159, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.SettingsTab.addTab(self.tabFont, "")
        self.tabArea = QtWidgets.QWidget()
        self.tabArea.setObjectName("tabArea")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabArea)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.LineToleranceLabel = QtWidgets.QLabel(self.tabArea)
        self.LineToleranceLabel.setObjectName("LineToleranceLabel")
        self.verticalLayout_4.addWidget(self.LineToleranceLabel)
        self.LineToleranceEdit = QtWidgets.QLineEdit(self.tabArea)
        self.LineToleranceEdit.setObjectName("LineToleranceEdit")
        self.verticalLayout_4.addWidget(self.LineToleranceEdit)
        self.AreaToleranceLabel = QtWidgets.QLabel(self.tabArea)
        self.AreaToleranceLabel.setObjectName("AreaToleranceLabel")
        self.verticalLayout_4.addWidget(self.AreaToleranceLabel)
        self.AreaToleranceEdit = QtWidgets.QLineEdit(self.tabArea)
        self.AreaToleranceEdit.setObjectName("AreaToleranceEdit")
        self.verticalLayout_4.addWidget(self.AreaToleranceEdit)
        self.MaxIterationLabel = QtWidgets.QLabel(self.tabArea)
        self.MaxIterationLabel.setObjectName("MaxIterationLabel")
        self.verticalLayout_4.addWidget(self.MaxIterationLabel)
        self.MaxIterationEdit = QtWidgets.QLineEdit(self.tabArea)
        self.MaxIterationEdit.setObjectName("MaxIterationEdit")
        self.verticalLayout_4.addWidget(self.MaxIterationEdit)
        spacerItem3 = QtWidgets.QSpacerItem(20, 147, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.SettingsTab.addTab(self.tabArea, "")
        self.tabUnits = QtWidgets.QWidget()
        self.tabUnits.setObjectName("tabUnits")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabUnits)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.tabUnits)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.comboDistanceStore = QtWidgets.QComboBox(self.groupBox)
        self.comboDistanceStore.setObjectName("comboDistanceStore")
        self.comboDistanceStore.addItem("")
        self.comboDistanceStore.addItem("")
        self.comboDistanceStore.addItem("")
        self.verticalLayout_7.addWidget(self.comboDistanceStore)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.comboDistanceDisplay = QtWidgets.QComboBox(self.groupBox)
        self.comboDistanceDisplay.setObjectName("comboDistanceDisplay")
        self.comboDistanceDisplay.addItem("")
        self.comboDistanceDisplay.addItem("")
        self.comboDistanceDisplay.addItem("")
        self.verticalLayout_7.addWidget(self.comboDistanceDisplay)
        spacerItem4 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabUnits)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.comboAngleStore = QtWidgets.QComboBox(self.groupBox_2)
        self.comboAngleStore.setObjectName("comboAngleStore")
        self.comboAngleStore.addItem("")
        self.comboAngleStore.addItem("")
        self.comboAngleStore.addItem("")
        self.verticalLayout_6.addWidget(self.comboAngleStore)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.comboAngleDisplay = QtWidgets.QComboBox(self.groupBox_2)
        self.comboAngleDisplay.setObjectName("comboAngleDisplay")
        self.comboAngleDisplay.addItem("")
        self.comboAngleDisplay.addItem("")
        self.comboAngleDisplay.addItem("")
        self.comboAngleDisplay.addItem("")
        self.verticalLayout_6.addWidget(self.comboAngleDisplay)
        spacerItem5 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.SettingsTab.addTab(self.tabUnits, "")
        self.verticalLayout.addWidget(self.SettingsTab)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.OKButton = QtWidgets.QPushButton(PluginSettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OKButton.sizePolicy().hasHeightForWidth())
        self.OKButton.setSizePolicy(sizePolicy)
        self.OKButton.setObjectName("OKButton")
        self.horizontalLayout.addWidget(self.OKButton)
        self.CancelButton = QtWidgets.QPushButton(PluginSettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CancelButton.sizePolicy().hasHeightForWidth())
        self.CancelButton.setSizePolicy(sizePolicy)
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout.addWidget(self.CancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PluginSettingsDialog)
        self.SettingsTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PluginSettingsDialog)
        PluginSettingsDialog.setTabOrder(self.SettingsTab, self.HomeDirEdit)
        PluginSettingsDialog.setTabOrder(self.HomeDirEdit, self.HomeDirButton)
        PluginSettingsDialog.setTabOrder(self.HomeDirButton, self.LogPathEdit)
        PluginSettingsDialog.setTabOrder(self.LogPathEdit, self.LogPathButton)
        PluginSettingsDialog.setTabOrder(self.LogPathButton, self.GamaPathEdit)
        PluginSettingsDialog.setTabOrder(self.GamaPathEdit, self.GamaPathButton)
        PluginSettingsDialog.setTabOrder(self.GamaPathButton, self.PlotTemplateDirEdit)
        PluginSettingsDialog.setTabOrder(self.PlotTemplateDirEdit, self.PlotTemplateDirButton)
        PluginSettingsDialog.setTabOrder(self.PlotTemplateDirButton, self.FontNameCombo)
        PluginSettingsDialog.setTabOrder(self.FontNameCombo, self.FontSizeCombo)
        PluginSettingsDialog.setTabOrder(self.FontSizeCombo, self.LineToleranceEdit)
        PluginSettingsDialog.setTabOrder(self.LineToleranceEdit, self.AreaToleranceEdit)
        PluginSettingsDialog.setTabOrder(self.AreaToleranceEdit, self.MaxIterationEdit)
        PluginSettingsDialog.setTabOrder(self.MaxIterationEdit, self.comboDistanceStore)
        PluginSettingsDialog.setTabOrder(self.comboDistanceStore, self.comboDistanceDisplay)
        PluginSettingsDialog.setTabOrder(self.comboDistanceDisplay, self.comboAngleStore)
        PluginSettingsDialog.setTabOrder(self.comboAngleStore, self.comboAngleDisplay)
        PluginSettingsDialog.setTabOrder(self.comboAngleDisplay, self.OKButton)
        PluginSettingsDialog.setTabOrder(self.OKButton, self.CancelButton)

    def retranslateUi(self, PluginSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        PluginSettingsDialog.setWindowTitle(_translate("PluginSettingsDialog", "Plugin Settings"))
        self.HomeDirLabel.setToolTip(_translate("PluginSettingsDialog", "Default directory for loading fieldbooks."))
        self.HomeDirLabel.setText(_translate("PluginSettingsDialog", "Home directory"))
        self.HomeDirEdit.setToolTip(_translate("PluginSettingsDialog", "Default directory for loading fieldbooks."))
        self.HomeDirButton.setText(_translate("PluginSettingsDialog", "..."))
        self.LogPathLabel.setToolTip(_translate("PluginSettingsDialog", "Directory for log file."))
        self.LogPathLabel.setText(_translate("PluginSettingsDialog", "Path to log file"))
        self.LogPathEdit.setToolTip(_translate("PluginSettingsDialog", "Path for log file."))
        self.LogPathButton.setText(_translate("PluginSettingsDialog", "..."))
        self.LogPathLabel_2.setToolTip(_translate("PluginSettingsDialog", "Directory for log file."))
        self.LogPathLabel_2.setText(_translate("PluginSettingsDialog", "Path to GNU Gama executable"))
        self.GamaPathEdit.setToolTip(_translate("PluginSettingsDialog", "Full path to gama-local executable."))
        self.GamaPathButton.setText(_translate("PluginSettingsDialog", "..."))
        self.LogPathLabel_3.setToolTip(_translate("PluginSettingsDialog", "Directory for log file."))
        self.LogPathLabel_3.setText(_translate("PluginSettingsDialog", "Plot template directory"))
        self.PlotTemplateDirEdit.setToolTip(_translate("PluginSettingsDialog", "Path to template files for batch plotting."))
        self.PlotTemplateDirButton.setText(_translate("PluginSettingsDialog", "..."))
        self.SettingsTab.setTabText(self.SettingsTab.indexOf(self.tabDirectories), _translate("PluginSettingsDialog", "Directories"))
        self.FontLabel.setText(_translate("PluginSettingsDialog", "Monospace font used in the calculation results widgets on Linux. On Windows it is courier font."))
        self.FontNameLabel.setText(_translate("PluginSettingsDialog", "Font name"))
        self.FontSizeLabel.setText(_translate("PluginSettingsDialog", "Font size"))
        self.SettingsTab.setTabText(self.SettingsTab.indexOf(self.tabFont), _translate("PluginSettingsDialog", "Font"))
        self.LineToleranceLabel.setText(_translate("PluginSettingsDialog", "Snap tolerance"))
        self.LineToleranceEdit.setToolTip(_translate("PluginSettingsDialog", "Snapping tolerance to line tool."))
        self.AreaToleranceLabel.setText(_translate("PluginSettingsDialog", "Area tolerance"))
        self.AreaToleranceEdit.setToolTip(_translate("PluginSettingsDialog", "Area tolerance for area division."))
        self.MaxIterationLabel.setText(_translate("PluginSettingsDialog", "Max. iterations"))
        self.MaxIterationEdit.setToolTip(_translate("PluginSettingsDialog", "Maximal number of iterations for area division."))
        self.SettingsTab.setTabText(self.SettingsTab.indexOf(self.tabArea), _translate("PluginSettingsDialog", "Area division"))
        self.groupBox.setTitle(_translate("PluginSettingsDialog", "Distance"))
        self.label.setText(_translate("PluginSettingsDialog", "Store as"))
        self.comboDistanceStore.setItemText(0, _translate("PluginSettingsDialog", "Metres"))
        self.comboDistanceStore.setItemText(1, _translate("PluginSettingsDialog", "Imperial feet"))
        self.comboDistanceStore.setItemText(2, _translate("PluginSettingsDialog", "US survey feet"))
        self.label_2.setText(_translate("PluginSettingsDialog", "Display as"))
        self.comboDistanceDisplay.setItemText(0, _translate("PluginSettingsDialog", "Metres"))
        self.comboDistanceDisplay.setItemText(1, _translate("PluginSettingsDialog", "Imperial feet"))
        self.comboDistanceDisplay.setItemText(2, _translate("PluginSettingsDialog", "US survey feet"))
        self.groupBox_2.setTitle(_translate("PluginSettingsDialog", "Angle"))
        self.label_3.setText(_translate("PluginSettingsDialog", "Store as"))
        self.comboAngleStore.setItemText(0, _translate("PluginSettingsDialog", "Degrees"))
        self.comboAngleStore.setItemText(1, _translate("PluginSettingsDialog", "Radians"))
        self.comboAngleStore.setItemText(2, _translate("PluginSettingsDialog", "Gons/grads"))
        self.label_4.setText(_translate("PluginSettingsDialog", "Display as"))
        self.comboAngleDisplay.setItemText(0, _translate("PluginSettingsDialog", "Degrees minutes seconds"))
        self.comboAngleDisplay.setItemText(1, _translate("PluginSettingsDialog", "Decimal degrees"))
        self.comboAngleDisplay.setItemText(2, _translate("PluginSettingsDialog", "Radians"))
        self.comboAngleDisplay.setItemText(3, _translate("PluginSettingsDialog", "Gons/grads"))
        self.SettingsTab.setTabText(self.SettingsTab.indexOf(self.tabUnits), _translate("PluginSettingsDialog", "Units"))
        self.OKButton.setText(_translate("PluginSettingsDialog", "OK"))
        self.CancelButton.setText(_translate("PluginSettingsDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PluginSettingsDialog = QtWidgets.QDialog()
    ui = Ui_PluginSettingsDialog()
    ui.setupUi(PluginSettingsDialog)
    PluginSettingsDialog.show()
    sys.exit(app.exec_())

