# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'traverse_calc.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TraverseCalcDialog(object):
    def setupUi(self, TraverseCalcDialog):
        TraverseCalcDialog.setObjectName("TraverseCalcDialog")
        TraverseCalcDialog.resize(933, 535)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TraverseCalcDialog.sizePolicy().hasHeightForWidth())
        TraverseCalcDialog.setSizePolicy(sizePolicy)
        TraverseCalcDialog.setMinimumSize(QtCore.QSize(0, 0))
        TraverseCalcDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        TraverseCalcDialog.setAccessibleName("")
        TraverseCalcDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(TraverseCalcDialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.MessageBar = QtWidgets.QWidget(TraverseCalcDialog)
        self.MessageBar.setObjectName("MessageBar")
        self.verticalLayout_6.addWidget(self.MessageBar)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RadioGroup = QtWidgets.QGroupBox(TraverseCalcDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RadioGroup.sizePolicy().hasHeightForWidth())
        self.RadioGroup.setSizePolicy(sizePolicy)
        self.RadioGroup.setFlat(False)
        self.RadioGroup.setCheckable(False)
        self.RadioGroup.setObjectName("RadioGroup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.RadioGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ClosedRadio = QtWidgets.QRadioButton(self.RadioGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClosedRadio.sizePolicy().hasHeightForWidth())
        self.ClosedRadio.setSizePolicy(sizePolicy)
        self.ClosedRadio.setObjectName("ClosedRadio")
        self.buttonGroup = QtWidgets.QButtonGroup(TraverseCalcDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.ClosedRadio)
        self.verticalLayout.addWidget(self.ClosedRadio)
        self.LinkRadio = QtWidgets.QRadioButton(self.RadioGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LinkRadio.sizePolicy().hasHeightForWidth())
        self.LinkRadio.setSizePolicy(sizePolicy)
        self.LinkRadio.setObjectName("LinkRadio")
        self.buttonGroup.addButton(self.LinkRadio)
        self.verticalLayout.addWidget(self.LinkRadio)
        self.OpenRadio = QtWidgets.QRadioButton(self.RadioGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenRadio.sizePolicy().hasHeightForWidth())
        self.OpenRadio.setSizePolicy(sizePolicy)
        self.OpenRadio.setObjectName("OpenRadio")
        self.buttonGroup.addButton(self.OpenRadio)
        self.verticalLayout.addWidget(self.OpenRadio)
        spacerItem = QtWidgets.QSpacerItem(20, 106, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.RadioGroup)
        self.EndpointsGroup = QtWidgets.QGroupBox(TraverseCalcDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndpointsGroup.sizePolicy().hasHeightForWidth())
        self.EndpointsGroup.setSizePolicy(sizePolicy)
        self.EndpointsGroup.setObjectName("EndpointsGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.EndpointsGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.StartPointLabel = QtWidgets.QLabel(self.EndpointsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartPointLabel.sizePolicy().hasHeightForWidth())
        self.StartPointLabel.setSizePolicy(sizePolicy)
        self.StartPointLabel.setObjectName("StartPointLabel")
        self.verticalLayout_2.addWidget(self.StartPointLabel)
        self.StartPointComboBox = QtWidgets.QComboBox(self.EndpointsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartPointComboBox.sizePolicy().hasHeightForWidth())
        self.StartPointComboBox.setSizePolicy(sizePolicy)
        self.StartPointComboBox.setObjectName("StartPointComboBox")
        self.verticalLayout_2.addWidget(self.StartPointComboBox)
        self.EndPointLabel = QtWidgets.QLabel(self.EndpointsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndPointLabel.sizePolicy().hasHeightForWidth())
        self.EndPointLabel.setSizePolicy(sizePolicy)
        self.EndPointLabel.setObjectName("EndPointLabel")
        self.verticalLayout_2.addWidget(self.EndPointLabel)
        self.EndPointComboBox = QtWidgets.QComboBox(self.EndpointsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndPointComboBox.sizePolicy().hasHeightForWidth())
        self.EndPointComboBox.setSizePolicy(sizePolicy)
        self.EndPointComboBox.setObjectName("EndPointComboBox")
        self.verticalLayout_2.addWidget(self.EndPointComboBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 85, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.EndpointsGroup)
        self.PointsGroup = QtWidgets.QGroupBox(TraverseCalcDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PointsGroup.sizePolicy().hasHeightForWidth())
        self.PointsGroup.setSizePolicy(sizePolicy)
        self.PointsGroup.setObjectName("PointsGroup")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.PointsGroup)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.TargetPointsLabel = QtWidgets.QLabel(self.PointsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TargetPointsLabel.sizePolicy().hasHeightForWidth())
        self.TargetPointsLabel.setSizePolicy(sizePolicy)
        self.TargetPointsLabel.setObjectName("TargetPointsLabel")
        self.verticalLayout_4.addWidget(self.TargetPointsLabel)
        self.TargetList = QtWidgets.QListWidget(self.PointsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TargetList.sizePolicy().hasHeightForWidth())
        self.TargetList.setSizePolicy(sizePolicy)
        self.TargetList.setObjectName("TargetList")
        self.verticalLayout_4.addWidget(self.TargetList)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.AddButton = QtWidgets.QPushButton(self.PointsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddButton.sizePolicy().hasHeightForWidth())
        self.AddButton.setSizePolicy(sizePolicy)
        self.AddButton.setObjectName("AddButton")
        self.verticalLayout_3.addWidget(self.AddButton)
        self.UpButton = QtWidgets.QPushButton(self.PointsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UpButton.sizePolicy().hasHeightForWidth())
        self.UpButton.setSizePolicy(sizePolicy)
        self.UpButton.setObjectName("UpButton")
        self.verticalLayout_3.addWidget(self.UpButton)
        self.DownButton = QtWidgets.QPushButton(self.PointsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DownButton.sizePolicy().hasHeightForWidth())
        self.DownButton.setSizePolicy(sizePolicy)
        self.DownButton.setObjectName("DownButton")
        self.verticalLayout_3.addWidget(self.DownButton)
        self.RemoveButton = QtWidgets.QPushButton(self.PointsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemoveButton.sizePolicy().hasHeightForWidth())
        self.RemoveButton.setSizePolicy(sizePolicy)
        self.RemoveButton.setObjectName("RemoveButton")
        self.verticalLayout_3.addWidget(self.RemoveButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.OrderPointsLabel = QtWidgets.QLabel(self.PointsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OrderPointsLabel.sizePolicy().hasHeightForWidth())
        self.OrderPointsLabel.setSizePolicy(sizePolicy)
        self.OrderPointsLabel.setObjectName("OrderPointsLabel")
        self.verticalLayout_5.addWidget(self.OrderPointsLabel)
        self.OrderList = QtWidgets.QListWidget(self.PointsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OrderList.sizePolicy().hasHeightForWidth())
        self.OrderList.setSizePolicy(sizePolicy)
        self.OrderList.setObjectName("OrderList")
        self.verticalLayout_5.addWidget(self.OrderList)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout_3.addWidget(self.PointsGroup)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.ResultGroup = QtWidgets.QGroupBox(TraverseCalcDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ResultGroup.sizePolicy().hasHeightForWidth())
        self.ResultGroup.setSizePolicy(sizePolicy)
        self.ResultGroup.setObjectName("ResultGroup")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ResultGroup)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ResultTextBrowser = QtWidgets.QTextBrowser(self.ResultGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResultTextBrowser.sizePolicy().hasHeightForWidth())
        self.ResultTextBrowser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.ResultTextBrowser.setFont(font)
        self.ResultTextBrowser.setObjectName("ResultTextBrowser")
        self.horizontalLayout_4.addWidget(self.ResultTextBrowser)
        self.verticalLayout_6.addWidget(self.ResultGroup)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.HelpButton = QtWidgets.QPushButton(TraverseCalcDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HelpButton.sizePolicy().hasHeightForWidth())
        self.HelpButton.setSizePolicy(sizePolicy)
        self.HelpButton.setObjectName("HelpButton")
        self.horizontalLayout_2.addWidget(self.HelpButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.CalcButton = QtWidgets.QPushButton(TraverseCalcDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CalcButton.sizePolicy().hasHeightForWidth())
        self.CalcButton.setSizePolicy(sizePolicy)
        self.CalcButton.setObjectName("CalcButton")
        self.horizontalLayout_2.addWidget(self.CalcButton)
        self.ResetButton = QtWidgets.QPushButton(TraverseCalcDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResetButton.sizePolicy().hasHeightForWidth())
        self.ResetButton.setSizePolicy(sizePolicy)
        self.ResetButton.setObjectName("ResetButton")
        self.horizontalLayout_2.addWidget(self.ResetButton)
        self.CloseButton = QtWidgets.QPushButton(TraverseCalcDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CloseButton.sizePolicy().hasHeightForWidth())
        self.CloseButton.setSizePolicy(sizePolicy)
        self.CloseButton.setObjectName("CloseButton")
        self.horizontalLayout_2.addWidget(self.CloseButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)

        self.retranslateUi(TraverseCalcDialog)
        QtCore.QMetaObject.connectSlotsByName(TraverseCalcDialog)
        TraverseCalcDialog.setTabOrder(self.ClosedRadio, self.LinkRadio)
        TraverseCalcDialog.setTabOrder(self.LinkRadio, self.OpenRadio)
        TraverseCalcDialog.setTabOrder(self.OpenRadio, self.StartPointComboBox)
        TraverseCalcDialog.setTabOrder(self.StartPointComboBox, self.EndPointComboBox)
        TraverseCalcDialog.setTabOrder(self.EndPointComboBox, self.TargetList)
        TraverseCalcDialog.setTabOrder(self.TargetList, self.AddButton)
        TraverseCalcDialog.setTabOrder(self.AddButton, self.UpButton)
        TraverseCalcDialog.setTabOrder(self.UpButton, self.DownButton)
        TraverseCalcDialog.setTabOrder(self.DownButton, self.RemoveButton)
        TraverseCalcDialog.setTabOrder(self.RemoveButton, self.OrderList)
        TraverseCalcDialog.setTabOrder(self.OrderList, self.ResultTextBrowser)
        TraverseCalcDialog.setTabOrder(self.ResultTextBrowser, self.HelpButton)
        TraverseCalcDialog.setTabOrder(self.HelpButton, self.CalcButton)
        TraverseCalcDialog.setTabOrder(self.CalcButton, self.ResetButton)
        TraverseCalcDialog.setTabOrder(self.ResetButton, self.CloseButton)

    def retranslateUi(self, TraverseCalcDialog):
        _translate = QtCore.QCoreApplication.translate
        TraverseCalcDialog.setWindowTitle(_translate("TraverseCalcDialog", "Traverse Calculations"))
        self.RadioGroup.setTitle(_translate("TraverseCalcDialog", "Type"))
        self.ClosedRadio.setToolTip(_translate("TraverseCalcDialog", "Closed (polygonal or loop) traverse starts and finishes on the same known point."))
        self.ClosedRadio.setText(_translate("TraverseCalcDialog", "Closed Traverse"))
        self.LinkRadio.setToolTip(_translate("TraverseCalcDialog", "A closed link traverse joins two known points."))
        self.LinkRadio.setText(_translate("TraverseCalcDialog", "Link Traverse"))
        self.OpenRadio.setToolTip(_translate("TraverseCalcDialog", "An open (free) traverse starts on a known point and finishes on an unknown point."))
        self.OpenRadio.setText(_translate("TraverseCalcDialog", "Open Traverse"))
        self.EndpointsGroup.setTitle(_translate("TraverseCalcDialog", "Endpoints"))
        self.StartPointLabel.setText(_translate("TraverseCalcDialog", "Start Point"))
        self.EndPointLabel.setText(_translate("TraverseCalcDialog", "End Point"))
        self.PointsGroup.setTitle(_translate("TraverseCalcDialog", "Points"))
        self.TargetPointsLabel.setText(_translate("TraverseCalcDialog", "Target Points"))
        self.AddButton.setText(_translate("TraverseCalcDialog", "Add >"))
        self.UpButton.setText(_translate("TraverseCalcDialog", "Up"))
        self.DownButton.setText(_translate("TraverseCalcDialog", "Down"))
        self.RemoveButton.setText(_translate("TraverseCalcDialog", "< Remove"))
        self.OrderPointsLabel.setText(_translate("TraverseCalcDialog", "Order of Points"))
        self.ResultGroup.setTitle(_translate("TraverseCalcDialog", "Result of Traverse Calculations"))
        self.HelpButton.setText(_translate("TraverseCalcDialog", "Help"))
        self.CalcButton.setText(_translate("TraverseCalcDialog", "Calculate"))
        self.ResetButton.setText(_translate("TraverseCalcDialog", "Reset"))
        self.CloseButton.setText(_translate("TraverseCalcDialog", "Close"))
